name: Build and Deploy for CD

on:
  push:
    tags:
      - 'release/*'  # release/v1.2.3와 같은 태그에 대해서만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # 3. Grant execute permission for Gradle Wrapper
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # 4. Clean Gradle Cache (Optional)
      - name: Clean Gradle Cache
        run: ./gradlew clean

      # 5. Build the JAR file
      - name: Build with Gradle
        run: ./gradlew makeJar --no-daemon

      # 6. Upload the JAR file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar
