name: Build and Deploy for CD

on:
  release:
    types: [published]  # 'published' 타입은 Release가 생성되었을 때 트리거됩니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # 3. Grant execute permission for Gradle Wrapper
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # 4. Clean Gradle Cache (Optional)
      - name: Clean Gradle Cache
        run: ./gradlew clean

      # 5. Cache Gradle Wrapper and Dependencies
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6. Build the Project
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --no-configuration-cache

      # 7. Run Tests
      - name: Run Tests
        run: ./gradlew test --no-daemon

      # 8. Build the JAR file
      - name: Build with Gradle
        run: ./gradlew makeJar --no-daemon

      # 9. Upload the JAR file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar
