name: CI for Java with Gradle

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle # Gradle 의존성 캐싱

      # 3. Add Execution permission
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # 4. Clean Gradle Caches
      - name: Clean Gradle Cache
        run: ./gradlew clean

      # 5. Cache Gradle Wrapper and Dependencies
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6. Build the Project
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 7. Run Tests
      - name: Run Tests
        run: ./gradlew test --no-daemon

      # tmp. checking cwd
      - name: List generated files
        run: ls -R

      # 8. Upload Test report
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Report
          path: build/reports/tests/test/**